---
name: Aqua Trivy Docker Image Vulnerability Scanner
description: Scan a Docker image for vulnerabilities using Aqua Security's Trivy
inputs:
  image-ref:
    description: Docker image reference to scan
    required: true
    default: docker.io/my-organization/my-app:latest
  format:
    description: Output format
    required: true
    default: sarif
  output:
    description: Output file name
    required: true
    default: trivy-results.sarif

runs:
  using: composite
  steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.image-ref }}
        format: ${{ inputs.format }}
        output: ${{ inputs.output }}

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ inputs.output }}
