---
name: Login to ECR
description: ARN based login to AWS ecr
inputs:
  aws_region:
    required: false
    description: The aws region
    default: us-east-1

outputs:
  registry:
    description: The registry url
    value: ${{ steps.login-ecr.outputs.registry }}

## Permissions needed for this action
# permissions:
#   contents: write

runs:
  using: "composite"
  steps:
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Login to ECR (docker)
      uses: docker/login-action@v1
      with:
        registry: ${{ steps.login-ecr.outputs.registry }}
