name: CI
on:
  workflow_call:
    inputs:
      aws_assume_role_arn:
        type: string
        description: "ARN of the role to assume, this role must have permissions to create ECR registeries."
        required: true
      registry_name:
        type: string
        description: "Name of the ECR registry to validate/create."
        required: true
      aws_region:
        type: string
        description: "AWS region where the ECR registry is located."
        required: false
        default: "us-east-1"

# ## Permissions needed for this action
# permissions:
#   id-token: write
#   contents: read

jobs:
  ecr-validate:
    runs-on: ubuntu-20.04
    steps:
      ## Require permission to write to id-token
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.aws_assume_role_arn }}
          role-session-name: GitHub-Actions-OIDC-ECR
          role-duration-seconds: 1200
          aws-region: ${{ inputs.aws_region }}

      - name: Validate ECR
        uses: smipin/smip-ui/.github/actions/ecr-create@feature/gha
        with:
          registry_name: ${{ inputs.registry_name }}
          aws_region: ${{ inputs.aws_region }}
