name: CI - Pytest
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_PROD:
        description: "Github secret containig slack webhook for prod channel"
        required: true
  push:

jobs:
  continuous-integration:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code (including tags)
        uses: actions/checkout@v3

      - name: continuous-testing
        uses: zmynx/github-actions/.github/actions/python/pytest@feature/gha
        with:
          python_version: 3.10
          test_command: pytest -v poc/pytest/

  slack:
    needs: [continuous-integration]
    runs-on: ubuntu-20.04
    if: always()
    steps:
      - name: Send slack message
        uses: zmynx/github-actions/.github/actions/shared/send-slack-message@feature/gha
        with:
          result: ${{ needs.continuous-integration.result }}
          title: "CI result:"
          channel: spikerz-pipline
          slack_webhook: ${{ secrets.SLACK_WEBHOOK_PROD }}
