name: CI
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_PROD:
        description: "Github secret containig slack webhook for prod channel"
        required: true
  push:

jobs:
  continuous-integration:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code (including tags)
        uses: actions/checkout@v3

      #### Testing Skipped ####
      # - name: continuous-testing
      #   uses: zmynx/github-actions/.github/actions/npm-test@feature/gha
      #   with:
      #     node_version: 16
      #     test_command: npm run test
      #     force_install_dependencies: true

  slack:
    needs: [continuous-integration]
    runs-on: ubuntu-20.04
    if: always()
    steps:
      - name: Send slack message
        uses: zmynx/github-actions/.github/actions/send-slack-message@feature/gha
        with:
          result: ${{ needs.continuous-integration.result }}
          title: "CI result:"
          channel: spikerz-pipline
          slack_webhook: ${{ secrets.SLACK_WEBHOOK_PROD }}
