---
name: Docker Build, Scan and Push
on: [workflow_dispatch]
jobs:
  docker:
    runs-on: ubuntu-22.04
    env:
      DOCKER_IMAGE: docker-scanned:latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker build --file ./poc/docker-scan-trivy/Dockerfile --tag ${{ env.DOCKER_IMAGE }} ./poc/docker-scan-trivy

      - name: Scan Docker image
        uses: zMynxx/github-actions/.github/actions/shared/docker-scan-trivy@feature/gha
        with:
          image-ref: ${{ env.DOCKER_IMAGE }}

      #   - name: Build the image (Dockerfile)
      #     uses: docker/build-push-action@v2
      #     id: push-image
      #     with:
      #       context: ./poc/docker-scan-trivy
      #       file: Dockerfile
      #       push: true
      #       tags: ${{ env.DOCKER_IMAGE }}
      #       cache-from: type=gha
      #       cache-to: type=gha,mode=max
