---
name: Docker Build, Scan and Push
on: [workflow_dispatch]
jobs:
  docker:
    runs-on: ubuntu-22.04
    env:
      DOCKER_IMAGE: docker-scanned:latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the image (Dockerfile)
        uses: docker/build-push-action@v2
        id: build-image
        with:
          context: ./poc/docker-scan-trivy
          file: ./poc/docker-scan-trivy/Dockerfile
          push: false
          tags: ${{ env.DOCKER_IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Scan Docker image
        uses: zMynxx/github-actions/.github/actions/shared/docker-scan-trivy@feature/gha
        with:
          image-ref: ${{ env.DOCKER_IMAGE }}

      #   - name: Build the image (Dockerfile)
      #     uses: docker/build-push-action@v2
      #     id: push-image
      #     with:
      #       context: ./poc/docker-scan-trivy
      #       file: Dockerfile
      #       push: true
      #       tags: ${{ env.DOCKER_IMAGE }}
      #       cache-from: type=gha
      #       cache-to: type=gha,mode=max
