---
name: Test dynamic uses
on:
  workflow_dispatch:

jobs:
  check:
    name: Dynamic uses
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: jenseng/dynamic-uses@v1
        with:
          # now you can use expressions 🥳
          # uses: ${{ vars.ORG_NAME }}/${{ vars.REPO_NAME }}/.github/actions/git/check-merge@${{ vars.REF}}
          uses: ${{ format('{0}/{1}/.github/actions/git/git-config@{2}', vars.ORG_NAME,  vars.REPO_NAME, vars.REF) }}
          # # the `with` needs to be converted to a valid json string
          # with: '{ "node-version": 18 }'

      - uses: jenseng/dynamic-uses@v1
        with:
          uses: ${{ format('{0}/{1}/.github/actions/python/pytest@{2}', vars.ORG_NAME,  vars.REPO_NAME, vars.REF) }}
          with: '{ "requirements_file": "./poc/pytest/requirements.txt" }'

  # check2:
  #   name: Call reusable workflow
  #   uses: ${{format('{0}/{1}/.github/workflows/ci-pytest.yaml@{2}',vars.ORG_NAME,vars.REPO_NAME,vars.REF)}}
